---
- name: enable a network interface on a Juniper device
  ## We specify all here, but in the demo we can override this to rtr1-4
  hosts: all
  vars:
    ## Some example variables to allow us to shut down or bring up a network interface 
    interface_message: ""
    interface_name: "gr-0/0/0"

  gather_facts: no

  tasks:
  - name: Override device configuration of all interfaces with provided configuration
    junipernetworks.junos.junos_interfaces:
      config:
        - enabled: true
          name: "{{ interface_name }}"
          #speed: "800mbps"
      state: overridden
    