---
- name: Get running configuration
  hosts: all
  gather_facts: no

  tasks:
  - name: "get running configuration" 
    junipernetworks.junos.junos_facts:
      gather_network_resources: all
    register: junos_facts

  - name: "Debug print the variable junos_facts"
    ansible.builtin.debug:
      msg: "{{ junos_facts }}"
  
    
        


