---
- name: Get running configuration
  ## We specify all here, but in the demo we can override this to rtr1-4
  hosts: all
  gather_facts: no

  tasks:
  - name: "Gather facts about the JunOS system" 
    junipernetworks.junos.junos_facts:
      gather_network_resources: all
    register: junos_facts

  - name: "Debug print the variable junos_facts"
    ansible.builtin.debug:
      msg: "{{ junos_facts }}"
  
    
        


