---
- name: Get running configuration
  ## We specify all here, but in the demo we can override this to rtr1-4
  hosts: all
  gather_facts: no

  tasks:
  - name: "get running configuration from juniper"
    junipernetworks.junos.junos_command:
      commands:
        - show interfaces
    register: running_interfaces
  

  - name: "Debug print the interface configuration"
    ansible.builtin.debug:
      msg: "{{ running_interfaces }}"
  
    
        


