---
- hosts: 
  - juniper

- gather_facts: no 

- tasks:
    name: "get running configuration" 
    junipernetworks.junos.junos_command:
      commands:
        - show configuration | match system-global | display=yes
        - show configuration | match interfaces
        - show interfaces
        - show running-config
      wait_for:
        - result[0] contains Configuration
        - result[1] contains interfaces
    register: reply_junos
      


