---
- name: Get running configuration
  hosts: all
  gather_facts: yes

  tasks:
  - name: "get running configuration" 
    junipernetworks.junos.junos_command:
      commands:
        - show running-config

    register: reply_junos
        


