---
- name: Get running configuration
  ## We specify all here, but in the demo we can override this to rtr1-4
  hosts: all
  gather_facts: no

  tasks:
  - name: "get running configuration from juniper"
    junipernetworks.junos.junos_command:
      commands:
        - show configuration
    register: running_config
  

  - name: "Debug print the running configuration"
    ansible.builtin.debug:
      msg: "{{ running_config.stdout }}"
  
    
        


