---
- name: Update the JunOS banner from a template 
  ## We specify all here, but in the demo we can override this to rtr1-4
  hosts: all

  gather_facts: yes

  tasks:
  
  - name: "load the juniper banner from the template templates/banner.j2"
    junipernetworks.junos.junos_banner:
      banner: motd
      text: "{{ lookup('ansible.builtin.template', './templates/banner_template1.j2') }}"
      state: present
  
  - name: Print all available facts
    ansible.builtin.debug:
      var: ansible_facts
    
        


