---
- name: Get running configuration
  ## We specify all here, but in the demo we can override this to rtr1-4
  hosts: all
  vars:
    interface_decription:

  gather_facts: no

  tasks:
  - name: Configure a new interface
    junipernetworks.junos.junos_interfaces:
    config:
      - name: ge-0/0/1
        description: Configured by Ansible-1
        enabled: true
        units:
          - name: 0
            description: "This is logical intf unit0"
        mtu: 1800
      - name: ge-0/0/2
        description: Configured by Ansible-2
        enabled: false
    state: merged

  - name: "Debug print the interface configuration"
    ansible.builtin.debug:
      msg: "{{ mryinterfaces.gathered }}"
    
        


