---
- name: Get running configuration
  ## We specify all here, but in the demo we can override this to rtr1-4
  hosts: all
  vars:
    interface_decription:

  gather_facts: no

  tasks:
  - name: Configure a new interface
    junipernetworks.junos.junos_interfaces:
      config:
        - name: gr-0/0/0
          description: Configured by Ansible-2
          enabled: false
      state: merged
    
        


